---
title: "R Notebook"
output: html_notebook
---

# load libraries
```{r libraries}
library(ggplot2)
library(leaflet)
```


# import

```{r import }
# here() to define relative path based on project root 
lhd_tiles_geojson_path <- here::here("data", "lhd_tiles_1km_epsg25833.geojson") 

print(lhd_tiles_geojson_path)


# function st_read
lhd_tiles_sf <- sf::st_read(lhd_tiles_geojson_path)
```


# convert sf to data.table
```{r convert to data.table}
# convert to data.table as firstly I do mainly data manipulation and plotting
lhd_tiles_dt <- data.table::as.data.table(lhd_tiles_sf)
```

# test aggregation
```{r aggregate}
# convert to data.table as firstly I do mainly data manipulation and plotting
lhd_north_aggr <- lhd_tiles_dt[, .(count_cells = .N), by= c("North")]
```



# plot histogram
```{r plot histogram}

plot_histo <- ggplot2::ggplot(lhd_north_aggr, ggplot2::aes(x = North, y = count_cells, fill = count_cells)) +
  ggplot2::theme_bw()+
  ggplot2::geom_bar(stat = "identity", width = 0.7) 

plot_histo



```
# plot map 

# Note: leaflet works with RGB rasters or tiles, so we convert using rasterImage

```{r plot grid}

# Make sure the data is in WGS84 (lat/lon)
lhd_tiles_sf <- sf::st_transform(lhd_tiles_sf, crs = 4326)

leaflet_plot <- leaflet(options = leafletOptions(minZoom = 2)) %>%
  addProviderTiles("CartoDB.Positron") %>%  # nice, clean basemap
  addPolygons(data= lhd_tiles_sf, color = "green")

leaflet_plot




```
